server:
  port: 8880


# https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html
# HTTP basic authentication is automatically added to your eureka client if one of the eureka.client.serviceUrl.defaultZone URLs has credentials embedded in it
eureka:
  client:
    serviceUrl:
      defaultZone: http://${myconfig.eureka.username}:${myconfig.eureka.password}@localhost:8761/eureka


